repos:
-   repo: local
    hooks:
    -   id: i18n-types
        name: generate i18n types
        entry: pnpm run i18n
        language: system
        pass_filenames: false
        always_run: true
